---
- name: Perform update of APT cache
  hosts: mail_servers
  become: true
  tasks:
  - name: Run apt-get update
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name:
    command: apt list --upgradable
    register: updates
  - debug: var=updates.stdout_lines
