---
- name: Perform full APT upgrade
  hosts: mail_servers
  become: true
  tasks:
  - name: Upgrade all installed packages
    apt:
      upgrade: dist
      force_apt_get: yes
      autoremove: yes
